// actionType.js

export const BOOK_FETCH_SUCCESS = "BOOK_FETCH_SUCCESS";
export const BOOK_FETCH_ERROR = "BOOK_FETCH_ERROR";

export const BOOK_CREATE_SUCCESS = "BOOK_CREATE_SUCCESS";

export const BOOK_UPDATE_SUCCESS = "BOOK_UPDATE_SUCCESS";

export const BOOK_DELETE_SUCCESS = "BOOK_DELETE_SUCCESS";

export const BOOK_SEARCH_SUCCESS = "BOOK_SEARCH_SUCCESS";
